/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectionPoolTest.java
 *
 * Created on 2011-7-28, 15:12:03
 */
package pb.data;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * @author maqiang
 */
public class ConnectionPoolTest extends javax.swing.JFrame
{
    private ConnectionPool pool;
    private PoolConnector  connector1;
    private PoolConnector  connector2;
    private PoolConnector  connector3;
    private PoolConnector  connector4;
    private PoolConnector  connector5;
    private PoolConnector  connector6;
    private PoolConnector  connector7;
    private PoolConnector  connector8;
    private PoolConnector  connector9;
    private PoolConnector  connector10;

    /** Creates new form ConnectionPoolTest */
    public ConnectionPoolTest()
    {
        initComponents();

        this.connectUrlTextArea.setText("jdbc:oracle:thin:@192.168.1.210:1521:orcl");
        this.userNameTextField.setText("bms");
        this.userPasswordField.setText("bms");


    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        conectedLabel1=new javax.swing.JLabel();
        connectButton1=new javax.swing.JButton();
        closeButton1=new javax.swing.JButton();
        connectButton2=new javax.swing.JButton();
        conectedLabel2=new javax.swing.JLabel();
        closeButton2=new javax.swing.JButton();
        connectButton3=new javax.swing.JButton();
        conectedLabel3=new javax.swing.JLabel();
        closeButton3=new javax.swing.JButton();
        connectButton4=new javax.swing.JButton();
        conectedLabel4=new javax.swing.JLabel();
        closeButton4=new javax.swing.JButton();
        connectButton5=new javax.swing.JButton();
        conectedLabel5=new javax.swing.JLabel();
        closeButton5=new javax.swing.JButton();
        connectButton6=new javax.swing.JButton();
        conectedLabel6=new javax.swing.JLabel();
        closeButton6=new javax.swing.JButton();
        connectButton7=new javax.swing.JButton();
        conectedLabel7=new javax.swing.JLabel();
        closeButton7=new javax.swing.JButton();
        connectButton8=new javax.swing.JButton();
        conectedLabel8=new javax.swing.JLabel();
        closeButton8=new javax.swing.JButton();
        connectButton9=new javax.swing.JButton();
        conectedLabel9=new javax.swing.JLabel();
        closeButton9=new javax.swing.JButton();
        connectButton10=new javax.swing.JButton();
        conectedLabel10=new javax.swing.JLabel();
        closeButton10=new javax.swing.JButton();
        connectUrlLabel=new javax.swing.JLabel();
        jScrollPane1=new javax.swing.JScrollPane();
        connectUrlTextArea=new javax.swing.JTextArea();
        userNameLabel=new javax.swing.JLabel();
        userNameTextField=new javax.swing.JTextField();
        userPassLabel=new javax.swing.JLabel();
        userPasswordField=new javax.swing.JPasswordField();
        createPoolButton=new javax.swing.JButton();
        refreshButton=new javax.swing.JButton();
        clearButton=new javax.swing.JButton();
        statusLabel=new javax.swing.JLabel();
        statusDisplayLabel=new javax.swing.JLabel();
        testConnectButton=new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conectedLabel1.setText("未连接！");

        connectButton1.setText("连接");
        connectButton1.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton1MouseClicked(evt);
                    }
                }
        );

        closeButton1.setText("关闭");
        closeButton1.setEnabled(false);
        closeButton1.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton1MouseClicked(evt);
                    }
                }
        );

        connectButton2.setText("连接");
        connectButton2.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton2MouseClicked(evt);
                    }
                }
        );

        conectedLabel2.setText("未连接！");

        closeButton2.setText("关闭");
        closeButton2.setEnabled(false);
        closeButton2.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton2MouseClicked(evt);
                    }
                }
        );

        connectButton3.setText("连接");
        connectButton3.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton3MouseClicked(evt);
                    }
                }
        );

        conectedLabel3.setText("未连接！");

        closeButton3.setText("关闭");
        closeButton3.setEnabled(false);
        closeButton3.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton3MouseClicked(evt);
                    }
                }
        );

        connectButton4.setText("连接");
        connectButton4.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton4MouseClicked(evt);
                    }
                }
        );

        conectedLabel4.setText("未连接！");

        closeButton4.setText("关闭");
        closeButton4.setEnabled(false);
        closeButton4.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton4MouseClicked(evt);
                    }
                }
        );

        connectButton5.setText("连接");
        connectButton5.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton5MouseClicked(evt);
                    }
                }
        );

        conectedLabel5.setText("未连接！");

        closeButton5.setText("关闭");
        closeButton5.setEnabled(false);
        closeButton5.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton5MouseClicked(evt);
                    }
                }
        );

        connectButton6.setText("连接");
        connectButton6.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton6MouseClicked(evt);
                    }
                }
        );

        conectedLabel6.setText("未连接！");

        closeButton6.setText("关闭");
        closeButton6.setEnabled(false);
        closeButton6.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton6MouseClicked(evt);
                    }
                }
        );

        connectButton7.setText("连接");
        connectButton7.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton7MouseClicked(evt);
                    }
                }
        );

        conectedLabel7.setText("未连接！");

        closeButton7.setText("关闭");
        closeButton7.setEnabled(false);
        closeButton7.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton7MouseClicked(evt);
                    }
                }
        );

        connectButton8.setText("连接");
        connectButton8.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton8MouseClicked(evt);
                    }
                }
        );

        conectedLabel8.setText("未连接！");

        closeButton8.setText("关闭");
        closeButton8.setEnabled(false);
        closeButton8.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton8MouseClicked(evt);
                    }
                }
        );

        connectButton9.setText("连接");
        connectButton9.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton9MouseClicked(evt);
                    }
                }
        );

        conectedLabel9.setText("未连接！");

        closeButton9.setText("关闭");
        closeButton9.setEnabled(false);
        closeButton9.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton9MouseClicked(evt);
                    }
                }
        );

        connectButton10.setText("连接");
        connectButton10.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        connectButton10MouseClicked(evt);
                    }
                }
        );

        conectedLabel10.setText("未连接！");

        closeButton10.setText("关闭");
        closeButton10.setEnabled(false);
        closeButton10.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        closeButton10MouseClicked(evt);
                    }
                }
        );

        connectUrlLabel.setText("JDBC URL：");

        connectUrlTextArea.setColumns(20);
        connectUrlTextArea.setLineWrap(true);
        connectUrlTextArea.setRows(3);
        jScrollPane1.setViewportView(connectUrlTextArea);

        userNameLabel.setText("用户：");

        userNameTextField.setFont(new java.awt.Font("宋体",0,14));
        userNameTextField.setToolTipText("登录用户名");

        userPassLabel.setText("密码：");

        userPasswordField.setFont(new java.awt.Font("宋体",0,14));
        userPasswordField.setToolTipText("登录密码");

        createPoolButton.setText("创建");
        createPoolButton.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        createPoolButtonMouseClicked(evt);
                    }
                }
        );

        refreshButton.setText("刷新");
        refreshButton.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        refreshButtonMouseClicked(evt);
                    }
                }
        );

        clearButton.setText("清空");

        statusLabel.setText("状态：");

        statusDisplayLabel.setText("未创建连接池！");

        testConnectButton.setText("测试");
        testConnectButton.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        testConnectButtonMouseClicked(evt);
                    }
                }
        );

        javax.swing.GroupLayout layout=new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING
                                                                                )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton5
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton5
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton4
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton4
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton3
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton3
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton2
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton2
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton1
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton1
                                                                                                        )
                                                                                        )
                                                                        )
                                                                        .addGap(46,46,46)
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING
                                                                                )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel10,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton10
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton10
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel9,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton9
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton9
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel8,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton8
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton8
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel7,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton7
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton7
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                conectedLabel6,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                58,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                connectButton6
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                closeButton6
                                                                                                        )
                                                                                        )
                                                                        )
                                                        )
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                layout.createSequentialGroup()
                                                                        .addGap(32,32,32)
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING
                                                                                )
                                                                                        .addComponent(connectUrlLabel)
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addGroup(
                                                                                                                layout.createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING
                                                                                                                )
                                                                                                                        .addComponent(
                                                                                                                                statusLabel
                                                                                                                        )
                                                                                                                        .addComponent(
                                                                                                                                userNameLabel
                                                                                                                        )
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                        )
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING
                                                                                )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addGroup(
                                                                                                                layout.createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING
                                                                                                                )
                                                                                                                        .addComponent(
                                                                                                                                jScrollPane1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                377,
                                                                                                                                Short.MAX_VALUE
                                                                                                                        )
                                                                                                                        .addGroup(
                                                                                                                                layout.createSequentialGroup()
                                                                                                                                        .addComponent(
                                                                                                                                                userNameTextField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                163,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                                                        )
                                                                                                                                        .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                                                        )
                                                                                                                                        .addComponent(
                                                                                                                                                userPassLabel
                                                                                                                                        )
                                                                                                                                        .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                                                        )
                                                                                                                                        .addComponent(
                                                                                                                                                userPasswordField,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                170,
                                                                                                                                                Short.MAX_VALUE
                                                                                                                                        )
                                                                                                                        )
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                testConnectButton
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                createPoolButton
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                refreshButton
                                                                                                        )
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                clearButton
                                                                                                        )
                                                                                        )
                                                                                        .addComponent(
                                                                                                statusDisplayLabel,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                377,Short.MAX_VALUE
                                                                                        )
                                                                        )
                                                        )
                                        )
                                        .addGap(40,40,40)
                        )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(connectUrlLabel)
                                                        .addComponent(
                                                                jScrollPane1,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                userNameTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(userNameLabel)
                                                        .addComponent(userPassLabel)
                                                        .addComponent(
                                                                userPasswordField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(createPoolButton)
                                                        .addComponent(refreshButton)
                                                        .addComponent(clearButton)
                                                        .addComponent(testConnectButton)
                                        )
                                        .addGap(18,18,18)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel6)
                                                                                        .addComponent(connectButton6)
                                                                                        .addComponent(closeButton6)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel7)
                                                                                        .addComponent(connectButton7)
                                                                                        .addComponent(closeButton7)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel8)
                                                                                        .addComponent(connectButton8)
                                                                                        .addComponent(closeButton8)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel9)
                                                                                        .addComponent(connectButton9)
                                                                                        .addComponent(closeButton9)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel10)
                                                                                        .addComponent(connectButton10)
                                                                                        .addComponent(closeButton10)
                                                                        )
                                                        )
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel1)
                                                                                        .addComponent(connectButton1)
                                                                                        .addComponent(closeButton1)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel2)
                                                                                        .addComponent(connectButton2)
                                                                                        .addComponent(closeButton2)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel3)
                                                                                        .addComponent(connectButton3)
                                                                                        .addComponent(closeButton3)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel4)
                                                                                        .addComponent(connectButton4)
                                                                                        .addComponent(closeButton4)
                                                                        )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED
                                                                        )
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE
                                                                                )
                                                                                        .addComponent(conectedLabel5)
                                                                                        .addComponent(connectButton5)
                                                                                        .addComponent(closeButton5)
                                                                        )
                                                        )
                                        )
                                        .addGap(18,18,18)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(statusLabel)
                                                        .addComponent(statusDisplayLabel)
                                        )
                                        .addContainerGap(26,Short.MAX_VALUE)
                        )
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //测试数据库连接按钮事件
    private void testConnectButtonMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_testConnectButtonMouseClicked
        //获取连接属性值
        String url=this.connectUrlTextArea.getText();
        String username=this.userNameTextField.getText();
        char[] userpass=this.userPasswordField.getPassword();

        //连接数据库
        Connector connecter=new PoolJdbcConnector(url,username,String.valueOf(userpass));
        connecter.connect();
        if(connecter.isConnected())
        {
            this.statusDisplayLabel.setText("！测试连接成功");
        }
        else
        {
            this.statusDisplayLabel.setText("！"+connecter.getError());
        }

        connecter.close();
        connecter=null;
    }//GEN-LAST:event_testConnectButtonMouseClicked

    //创建连接池按钮事件
    private void createPoolButtonMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_createPoolButtonMouseClicked
        //获取连接属性值
        String url=this.connectUrlTextArea.getText();
        String username=this.userNameTextField.getText();
        char[] userpass=this.userPasswordField.getPassword();

        this.pool=new ConnectionPool(url,username,String.valueOf(userpass));
        this.pool.setInitialConnectNumber(5);
        this.pool.setIncrementalConnectNumber(1);
        this.pool.setMaxConnectNumber(8);
        this.pool.setMaxWaitTime(0);
        this.pool.initConnectionPool();

        this.statusDisplayLabel.setText(
                "总数-"+this.pool.getCurrentTotalConnectNumber()
                        +";空闲数-"+this.pool.getCurrentIdleThreadNumber()
        );
    }//GEN-LAST:event_createPoolButtonMouseClicked

    private void connectButton1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton1MouseClicked
        this.connector1=this.connectHandle(connectButton1,closeButton1,this.conectedLabel1,connector1);
    }//GEN-LAST:event_connectButton1MouseClicked

    private void connectButton2MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton2MouseClicked
        this.connector2=this.connectHandle(connectButton2,closeButton2,this.conectedLabel2,connector2);
    }//GEN-LAST:event_connectButton2MouseClicked

    private void connectButton3MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton3MouseClicked
        this.connector3=this.connectHandle(connectButton3,closeButton3,this.conectedLabel3,connector3);
    }//GEN-LAST:event_connectButton3MouseClicked

    private void connectButton4MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton4MouseClicked
        this.connector4=this.connectHandle(connectButton4,closeButton4,this.conectedLabel4,connector4);
    }//GEN-LAST:event_connectButton4MouseClicked

    private void connectButton5MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton5MouseClicked
        this.connector5=this.connectHandle(connectButton5,closeButton5,this.conectedLabel5,connector5);
    }//GEN-LAST:event_connectButton5MouseClicked

    private void connectButton6MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton6MouseClicked
        this.connector6=this.connectHandle(connectButton6,closeButton6,this.conectedLabel6,connector6);
    }//GEN-LAST:event_connectButton6MouseClicked

    private void connectButton7MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton7MouseClicked
        this.connector7=this.connectHandle(connectButton7,closeButton7,this.conectedLabel7,connector7);
    }//GEN-LAST:event_connectButton7MouseClicked

    private void connectButton8MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton8MouseClicked
        this.connector8=this.connectHandle(connectButton8,closeButton8,this.conectedLabel8,connector8);
    }//GEN-LAST:event_connectButton8MouseClicked

    private void connectButton9MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton9MouseClicked
        this.connector9=this.connectHandle(connectButton9,closeButton9,this.conectedLabel9,connector9);
    }//GEN-LAST:event_connectButton9MouseClicked

    private void connectButton10MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_connectButton10MouseClicked
        this.connector10=this.connectHandle(connectButton10,closeButton10,this.conectedLabel10,connector10);
    }//GEN-LAST:event_connectButton10MouseClicked

    private void closeButton1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton1MouseClicked
        this.closeHandle(connectButton1,closeButton1,this.conectedLabel1,connector1);
    }//GEN-LAST:event_closeButton1MouseClicked

    private void closeButton2MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton2MouseClicked
        this.closeHandle(connectButton2,closeButton2,this.conectedLabel2,connector2);
    }//GEN-LAST:event_closeButton2MouseClicked

    private void closeButton3MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton3MouseClicked
        this.closeHandle(connectButton3,closeButton3,this.conectedLabel3,connector3);
    }//GEN-LAST:event_closeButton3MouseClicked

    private void closeButton4MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton4MouseClicked
        this.closeHandle(connectButton4,closeButton4,this.conectedLabel4,connector4);
    }//GEN-LAST:event_closeButton4MouseClicked

    private void closeButton5MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton5MouseClicked
        this.closeHandle(connectButton5,closeButton5,this.conectedLabel5,connector5);
    }//GEN-LAST:event_closeButton5MouseClicked

    private void closeButton6MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton6MouseClicked
        this.closeHandle(connectButton6,closeButton6,this.conectedLabel6,connector6);
    }//GEN-LAST:event_closeButton6MouseClicked

    private void closeButton7MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton7MouseClicked
        this.closeHandle(connectButton7,closeButton7,this.conectedLabel7,connector7);
    }//GEN-LAST:event_closeButton7MouseClicked

    private void closeButton8MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton8MouseClicked
        this.closeHandle(connectButton8,closeButton8,this.conectedLabel8,connector8);
    }//GEN-LAST:event_closeButton8MouseClicked

    private void closeButton9MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton9MouseClicked
        this.closeHandle(connectButton9,closeButton9,this.conectedLabel9,connector9);
    }//GEN-LAST:event_closeButton9MouseClicked

    private void closeButton10MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_closeButton10MouseClicked
        this.closeHandle(connectButton10,closeButton10,this.conectedLabel10,connector10);
    }//GEN-LAST:event_closeButton10MouseClicked

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_refreshButtonMouseClicked

    }//GEN-LAST:event_refreshButtonMouseClicked


    //获取空闲连接处理方法
    private PoolConnector connectHandle
    (JButton connect,JButton close,JLabel label,PoolConnector connector)
    {
        //获取空闲连接
        connector=this.pool.getConnection();
        boolean success=(connector!=null);

        if(success)
        {
            //设置按钮状态
            connect.setEnabled(false);
            close.setEnabled(true);

            //显示连接状态
            label.setText("已连接！");

            //显示缓存区状态
            this.statusDisplayLabel.setText(
                    "总数-"+this.pool.getCurrentTotalConnectNumber()
                            +";空闲数-"+this.pool.getCurrentIdleThreadNumber()
            );
        }
        else
        {
            //设置按钮状态
            connect.setEnabled(true);
            close.setEnabled(false);

            //显示连接状态
            label.setText("未连接！");

            //显示缓存区状态
            this.statusDisplayLabel.setText(this.pool.getError());
        }


        return connector;
    }

    //关闭空闲连接处理方法
    private void closeHandle
    (JButton connect,JButton close,JLabel label,PoolConnector connector)
    {
        //获取空闲连接
        this.pool.returnConnection(connector);
        connector=null;

        //设置按钮状态
        connect.setEnabled(true);
        close.setEnabled(false);

        //显示连接状态
        label.setText("未连接！");

        //显示缓存区状态
        this.statusDisplayLabel.setText(
                "总数-"+this.pool.getCurrentTotalConnectNumber()
                        +";空闲数-"+this.pool.getCurrentIdleThreadNumber()
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(
                new Runnable()
                {

                    public void run()
                    {
                        new ConnectionPoolTest().setVisible(true);
                    }
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton        clearButton;
    private javax.swing.JButton        closeButton1;
    private javax.swing.JButton        closeButton10;
    private javax.swing.JButton        closeButton2;
    private javax.swing.JButton        closeButton3;
    private javax.swing.JButton        closeButton4;
    private javax.swing.JButton        closeButton5;
    private javax.swing.JButton        closeButton6;
    private javax.swing.JButton        closeButton7;
    private javax.swing.JButton        closeButton8;
    private javax.swing.JButton        closeButton9;
    private javax.swing.JLabel         conectedLabel1;
    private javax.swing.JLabel         conectedLabel10;
    private javax.swing.JLabel         conectedLabel2;
    private javax.swing.JLabel         conectedLabel3;
    private javax.swing.JLabel         conectedLabel4;
    private javax.swing.JLabel         conectedLabel5;
    private javax.swing.JLabel         conectedLabel6;
    private javax.swing.JLabel         conectedLabel7;
    private javax.swing.JLabel         conectedLabel8;
    private javax.swing.JLabel         conectedLabel9;
    private javax.swing.JButton        connectButton1;
    private javax.swing.JButton        connectButton10;
    private javax.swing.JButton        connectButton2;
    private javax.swing.JButton        connectButton3;
    private javax.swing.JButton        connectButton4;
    private javax.swing.JButton        connectButton5;
    private javax.swing.JButton        connectButton6;
    private javax.swing.JButton        connectButton7;
    private javax.swing.JButton        connectButton8;
    private javax.swing.JButton        connectButton9;
    private javax.swing.JLabel         connectUrlLabel;
    private javax.swing.JTextArea      connectUrlTextArea;
    private javax.swing.JButton        createPoolButton;
    private javax.swing.JScrollPane    jScrollPane1;
    private javax.swing.JButton        refreshButton;
    private javax.swing.JLabel         statusDisplayLabel;
    private javax.swing.JLabel         statusLabel;
    private javax.swing.JButton        testConnectButton;
    private javax.swing.JLabel         userNameLabel;
    private javax.swing.JTextField     userNameTextField;
    private javax.swing.JLabel         userPassLabel;
    private javax.swing.JPasswordField userPasswordField;
    // End of variables declaration//GEN-END:variables
}
