package pb.data;

/**
 * Jdbc数据库连接测试器，用于测试数据库连接
 *
 * @author proteanBear(马强)
 * @version 1.00 2011/04/13
 */
public class DataConnectTest extends javax.swing.JFrame
{
    /*------------------------- 开始：业务处理--------------------------*/
    /**
     * 域(私有)<br>
     * 名称:    connecter<br>
     * 描述:    数据连接器<br>
     */
    private Connector connecter;

    /**
     * 构造函数<br>
     * 描述：  创建窗口和对象
     */
    public DataConnectTest()
    {
        //创建窗口
        initComponents();
        this.setLocationRelativeTo(null);

        //设置默认值
        this.resetField();
    }

    /**
     * 主方法<br>
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(
                new Runnable()
                {
                    public void run()
                    {
                        new DataConnectTest().setVisible(true);
                    }
                }
        );
    }

    /**
     * 方法（私有）<br>
     * 名称:    dataFieldChange<br>
     * 描述:    连接参数改变处理方法，组合连接参数显示jdbc url<br>
     */
    private void dataFieldChange()
    {
        //获取连接属性
        String dataType=this.dataTypeComboBox.getSelectedItem().toString();
        String serverIp=this.dataServerIPTextField.getText();
        String serverPort=this.dataServerPortTextField.getText();
        int port=0;
        String dataName=this.dataNameTextField.getText();

        //判断属性值,并添加提示
        if("".equals(serverIp))
        {
            this.inforTextArea.setText("！必须填写数据库服务器主机地址");
        }
        else if("".equals(serverPort))
        {
            this.inforTextArea.setText("！必须填写数据库服务器服务端口");
        }
        else if("".equals(dataName))
        {
            this.inforTextArea.setText("！必须填写数据库名称");
        }
        else
        {
            this.inforTextArea.setText("");
        }

        if(!"".equals(serverPort)) port=Integer.parseInt(serverPort);

        this.connectUrlTextArea.setText(JdbcConnector.generateUrl(dataType,serverIp,port,dataName));
    }

    /**
     * 方法（私有）<br>
     * 名称:    pingConnect<br>
     * 描述:    测试数据库连接<br>
     */
    private void pingConnect()
    {
        //获取连接属性值
        String url=this.connectUrlTextArea.getText();
        String username=this.userNameTextField.getText();
        char[] userpass=this.userPasswordField.getPassword();

        //连接数据库
        this.connecter=new PoolJdbcConnector(url,username,String.valueOf(userpass));
        this.connecter.connect();
        if(this.connecter.isConnected())
        {
            this.inforTextArea.setText("！连接成功");
        }
        else
        {
            this.inforTextArea.setText("！"+this.connecter.getError());
        }

        this.connecter.close();
    }

    /**
     * 方法（私有）<br>
     * 名称:    resetFiled<br>
     * 描述:    重置输入框信息<br>
     */
    private void resetField()
    {
        this.dataTypeComboBox.setSelectedIndex(0);
        this.dataServerIPTextField.setText("");
        this.dataServerPortTextField.setText("");
        this.dataNameTextField.setText("");
        this.userNameTextField.setText("");
        this.userPasswordField.setText("");
        this.connectUrlTextArea.setText(JdbcConnector.generateUrl(JdbcConnector.DATABASE_MYSQL,"",0,""));
        this.inforTextArea.setText("填写数据库连接信息");
    }
    /*------------------------- 开始：业务处理--------------------------*/

    /*------------------------- 开始：界面（生成代码）--------------------------*/

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dataConnectFieldPanel=new javax.swing.JPanel();
        dataTypeLabel=new javax.swing.JLabel();
        dataServerPortLabel=new javax.swing.JLabel();
        dataServerPortTextField=new javax.swing.JTextField();
        dataServerIPLabel=new javax.swing.JLabel();
        dataServerIPTextField=new javax.swing.JTextField();
        dataTypeComboBox=new javax.swing.JComboBox();
        dataNameLabel=new javax.swing.JLabel();
        dataNameTextField=new javax.swing.JTextField();
        dataConnectUserPanel=new javax.swing.JPanel();
        userNameLabel=new javax.swing.JLabel();
        userNameTextField=new javax.swing.JTextField();
        userPassLabel=new javax.swing.JLabel();
        userPasswordField=new javax.swing.JPasswordField();
        dataConnectUrlPanel=new javax.swing.JPanel();
        connectUrlLabel=new javax.swing.JLabel();
        jScrollPane1=new javax.swing.JScrollPane();
        connectUrlTextArea=new javax.swing.JTextArea();
        pingButton=new javax.swing.JButton();
        resetButton=new javax.swing.JButton();
        jScrollPane2=new javax.swing.JScrollPane();
        inforTextArea=new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dataTypeLabel.setFont(new java.awt.Font("宋体",0,14));
        dataTypeLabel.setText("数据库类型：");

        dataServerPortLabel.setFont(new java.awt.Font("宋体",0,14));
        dataServerPortLabel.setText("端口：");

        dataServerPortTextField.setFont(new java.awt.Font("宋体",0,14));
        dataServerPortTextField.setToolTipText("数据库服务器服务端口");
        dataServerPortTextField.addFocusListener(
                new java.awt.event.FocusAdapter()
                {
                    public void focusLost(java.awt.event.FocusEvent evt)
                    {
                        dataServerPortTextFieldFocusLost(evt);
                    }
                }
        );

        dataServerIPLabel.setFont(new java.awt.Font("宋体",0,14));
        dataServerIPLabel.setText("主机：");

        dataServerIPTextField.setFont(new java.awt.Font("宋体",0,14));
        dataServerIPTextField.setToolTipText("数据库服务器主机或IP地址");
        dataServerIPTextField.addFocusListener(
                new java.awt.event.FocusAdapter()
                {
                    public void focusLost(java.awt.event.FocusEvent evt)
                    {
                        dataServerIPTextFieldFocusLost(evt);
                    }
                }
        );

        dataTypeComboBox.setFont(new java.awt.Font("宋体",0,14));
        dataTypeComboBox.setModel(
                new javax.swing.DefaultComboBoxModel(
                        new String[]{"MYSQL","ORACLE","SQLSERVER","ACCESS","ODBC","DB2","SYBASE","JAVADB"}
                )
        );
        dataTypeComboBox.setToolTipText("选择数据库的类型");
        dataTypeComboBox.addActionListener(
                new java.awt.event.ActionListener()
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                        dataTypeComboBoxActionPerformed(evt);
                    }
                }
        );

        dataNameLabel.setFont(new java.awt.Font("宋体",0,14));
        dataNameLabel.setText("数据库：");

        dataNameTextField.setFont(new java.awt.Font("宋体",0,14));
        dataNameTextField.setToolTipText("数据库名称");
        dataNameTextField.addFocusListener(
                new java.awt.event.FocusAdapter()
                {
                    public void focusLost(java.awt.event.FocusEvent evt)
                    {
                        dataNameTextFieldFocusLost(evt);
                    }
                }
        );

        javax.swing.GroupLayout dataConnectFieldPanelLayout=new javax.swing.GroupLayout(dataConnectFieldPanel);
        dataConnectFieldPanel.setLayout(dataConnectFieldPanelLayout);
        dataConnectFieldPanelLayout.setHorizontalGroup(
                dataConnectFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                dataConnectFieldPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                dataConnectFieldPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dataTypeLabel)
                                                        .addComponent(dataServerIPLabel)
                                                        .addComponent(dataServerPortLabel)
                                                        .addComponent(dataNameLabel)
                                        )
                                        .addGap(32,32,32)
                                        .addGroup(
                                                dataConnectFieldPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                dataServerIPTextField,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,315,Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                dataServerPortTextField,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,315,Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                dataNameTextField,javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                315,Short.MAX_VALUE
                                                        )
                                                        .addComponent(dataTypeComboBox,0,315,Short.MAX_VALUE)
                                        )
                                        .addContainerGap()
                        )
        );
        dataConnectFieldPanelLayout.setVerticalGroup(
                dataConnectFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                dataConnectFieldPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                dataConnectFieldPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(dataTypeLabel)
                                                        .addComponent(
                                                                dataTypeComboBox,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                dataConnectFieldPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(dataServerIPLabel)
                                                        .addComponent(
                                                                dataServerIPTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                dataConnectFieldPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(dataServerPortLabel)
                                                        .addComponent(
                                                                dataServerPortTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                dataConnectFieldPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(dataNameLabel)
                                                        .addComponent(
                                                                dataNameTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addContainerGap()
                        )
        );

        userNameLabel.setFont(new java.awt.Font("宋体",0,14));
        userNameLabel.setText("用户：");

        userNameTextField.setFont(new java.awt.Font("宋体",0,14));
        userNameTextField.setToolTipText("登录用户名");

        userPassLabel.setFont(new java.awt.Font("宋体",0,14));
        userPassLabel.setText("密码：");

        userPasswordField.setFont(new java.awt.Font("宋体",0,14)); // NOI18N
        userPasswordField.setToolTipText("登录密码");

        javax.swing.GroupLayout dataConnectUserPanelLayout=new javax.swing.GroupLayout(dataConnectUserPanel);
        dataConnectUserPanel.setLayout(dataConnectUserPanelLayout);
        dataConnectUserPanelLayout.setHorizontalGroup(
                dataConnectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                dataConnectUserPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                dataConnectUserPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(userNameLabel)
                                                        .addComponent(userPassLabel)
                                        )
                                        .addGap(73,73,73)
                                        .addGroup(
                                                dataConnectUserPanelLayout.createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING,false
                                                )
                                                        .addComponent(userPasswordField)
                                                        .addComponent(
                                                                userNameTextField,javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                316,Short.MAX_VALUE
                                                        )
                                        )
                                        .addContainerGap(13,Short.MAX_VALUE)
                        )
        );
        dataConnectUserPanelLayout.setVerticalGroup(
                dataConnectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                dataConnectUserPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                dataConnectUserPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(userNameLabel)
                                                        .addComponent(
                                                                userNameTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                dataConnectUserPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(userPassLabel)
                                                        .addComponent(
                                                                userPasswordField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                        )
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
                        )
        );

        dataConnectUrlPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        connectUrlLabel.setFont(new java.awt.Font("宋体",0,14));
        connectUrlLabel.setText("JDBC URL：");

        connectUrlTextArea.setColumns(20);
        connectUrlTextArea.setLineWrap(true);
        connectUrlTextArea.setRows(3);
        jScrollPane1.setViewportView(connectUrlTextArea);

        javax.swing.GroupLayout dataConnectUrlPanelLayout=new javax.swing.GroupLayout(dataConnectUrlPanel);
        dataConnectUrlPanel.setLayout(dataConnectUrlPanelLayout);
        dataConnectUrlPanelLayout.setHorizontalGroup(
                dataConnectUrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                dataConnectUrlPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(connectUrlLabel)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,44,Short.MAX_VALUE
                                        )
                                        .addComponent(
                                                jScrollPane1,javax.swing.GroupLayout.PREFERRED_SIZE,320,
                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addContainerGap()
                        )
        );
        dataConnectUrlPanelLayout.setVerticalGroup(
                dataConnectUrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                dataConnectUrlPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                dataConnectUrlPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jScrollPane1,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(connectUrlLabel)
                                        )
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
                        )
        );

        pingButton.setFont(new java.awt.Font("宋体",0,14));
        pingButton.setText("测试");
        pingButton.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        pingButtonMouseClicked(evt);
                    }
                }
        );

        resetButton.setFont(new java.awt.Font("宋体",0,14));
        resetButton.setText("重置");
        resetButton.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        resetButtonMouseClicked(evt);
                    }
                }
        );

        jScrollPane2.setBorder(null);
        jScrollPane2.setToolTipText("提示及错误信息");

        inforTextArea.setBackground(new java.awt.Color(240,240,240));
        inforTextArea.setColumns(20);
        inforTextArea.setEditable(false);
        inforTextArea.setFont(new java.awt.Font("Monospaced",0,14));
        inforTextArea.setLineWrap(true);
        inforTextArea.setRows(5);
        inforTextArea.setText("填写数据库连接信息");
        inforTextArea.setBorder(null);
        jScrollPane2.setViewportView(inforTextArea);

        javax.swing.GroupLayout layout=new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addGap(27,27,27)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING
                                                                                )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addGap(
                                                                                                                10,10,10
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                jScrollPane2,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                434,
                                                                                                                Short.MAX_VALUE
                                                                                                        )
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                304,
                                                                                                                Short.MAX_VALUE
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                pingButton
                                                                                                        )
                                                                                                        .addGap(
                                                                                                                18,18,18
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                resetButton
                                                                                                        )
                                                                                        )
                                                                        )
                                                                        .addGap(40,40,40)
                                                        )
                                                        .addGroup(
                                                                layout.createSequentialGroup()
                                                                        .addGroup(
                                                                                layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING
                                                                                )
                                                                                        .addGroup(
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                dataConnectFieldPanel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE
                                                                                                        )
                                                                                                        .addGap(3,3,3)
                                                                                        )
                                                                                        .addGroup(
                                                                                                layout.createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                        false
                                                                                                )
                                                                                                        .addComponent(
                                                                                                                dataConnectUrlPanel,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE
                                                                                                        )
                                                                                                        .addComponent(
                                                                                                                dataConnectUserPanel,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                                                                        )
                                                                                        )
                                                                        )
                                                                        .addGap(30,30,30)
                                                        )
                                        )
                        )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(
                                                dataConnectFieldPanel,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                dataConnectUserPanel,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addGap(18,18,18)
                                        .addComponent(
                                                dataConnectUrlPanel,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jScrollPane2,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                        )
                                        .addGap(28,28,28)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(resetButton)
                                                        .addComponent(pingButton)
                                        )
                                        .addGap(20,20,20)
                        )
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //数据库类型选择框选择事件
    private void dataTypeComboBoxActionPerformed(
            java.awt.event.ActionEvent evt)//GEN-FIRST:event_dataTypeComboBoxActionPerformed
    {//GEN-HEADEREND:event_dataTypeComboBoxActionPerformed
        this.dataFieldChange();
    }//GEN-LAST:event_dataTypeComboBoxActionPerformed

    //数据库主机输入框失去焦点事件
    private void dataServerIPTextFieldFocusLost(
            java.awt.event.FocusEvent evt)//GEN-FIRST:event_dataServerIPTextFieldFocusLost
    {//GEN-HEADEREND:event_dataServerIPTextFieldFocusLost
        this.dataFieldChange();
    }//GEN-LAST:event_dataServerIPTextFieldFocusLost

    //数据库端口输入框失去焦点事件
    private void dataServerPortTextFieldFocusLost(
            java.awt.event.FocusEvent evt)//GEN-FIRST:event_dataServerPortTextFieldFocusLost
    {//GEN-HEADEREND:event_dataServerPortTextFieldFocusLost
        this.dataFieldChange();
    }//GEN-LAST:event_dataServerPortTextFieldFocusLost

    //数据库名称输入框失去焦点事件
    private void dataNameTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_dataNameTextFieldFocusLost
    {//GEN-HEADEREND:event_dataNameTextFieldFocusLost
        this.dataFieldChange();
    }//GEN-LAST:event_dataNameTextFieldFocusLost

    //测试数据库连接按钮点击事件
    private void pingButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_pingButtonMouseClicked
    {//GEN-HEADEREND:event_pingButtonMouseClicked
        this.pingConnect();
    }//GEN-LAST:event_pingButtonMouseClicked

    //重置信息输入按钮点击事件
    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_resetButtonMouseClicked
    {//GEN-HEADEREND:event_resetButtonMouseClicked
        this.resetField();
    }//GEN-LAST:event_resetButtonMouseClicked

    //连接参数改变处理事件
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel         connectUrlLabel;
    private javax.swing.JTextArea      connectUrlTextArea;
    private javax.swing.JPanel         dataConnectFieldPanel;
    private javax.swing.JPanel         dataConnectUrlPanel;
    private javax.swing.JPanel         dataConnectUserPanel;
    private javax.swing.JLabel         dataNameLabel;
    private javax.swing.JTextField     dataNameTextField;
    private javax.swing.JLabel         dataServerIPLabel;
    private javax.swing.JTextField     dataServerIPTextField;
    private javax.swing.JLabel         dataServerPortLabel;
    private javax.swing.JTextField     dataServerPortTextField;
    private javax.swing.JComboBox      dataTypeComboBox;
    private javax.swing.JLabel         dataTypeLabel;
    private javax.swing.JTextArea      inforTextArea;
    private javax.swing.JScrollPane    jScrollPane1;
    private javax.swing.JScrollPane    jScrollPane2;
    private javax.swing.JButton        pingButton;
    private javax.swing.JButton        resetButton;
    private javax.swing.JLabel         userNameLabel;
    private javax.swing.JTextField     userNameTextField;
    private javax.swing.JLabel         userPassLabel;
    private javax.swing.JPasswordField userPasswordField;
    // End of variables declaration//GEN-END:variables
    /*------------------------- 结束：界面（生成代码）--------------------------*/
}