/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoveCalculator.java
 *
 * Created on 2011-11-24, 9:27:40
 */
package pb.text;

/**
 * @author maqiang
 */
public class LoveCalculator extends javax.swing.JFrame
{
    /**
     * 域(私有)<br>
     * 名称:    dp<br>
     * 描述:    日期处理对象<br>
     */
    private DateProcessor dp;

    /**
     * 域()<br>
     * 名称:    <br>
     * 描述:    <br>
     */
    private String curDate;

    private String knowDate;
    private String loveDate;
    private String marryDate;

    /** Creates new form LoveCalculator */
    public LoveCalculator()
    {
        initComponents();

        this.dp=new DateProcessor();
        this.curDate=this.dp.getCurrent();
        this.knowDate="2001-09-10";
        this.loveDate="2002-02-24";
        this.marryDate="2011-03-22";

        this.currentDateField.setText(curDate);
        this.knowDateField.setText(this.knowDate);
        this.loveDateField.setText(this.loveDate);
        this.marryDateField.setText(this.marryDate);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        loveDateLabel=new javax.swing.JLabel();
        loveDateField=new javax.swing.JTextField();
        marryDateField=new javax.swing.JTextField();
        marryDateLabel=new javax.swing.JLabel();
        currentDateLabel=new javax.swing.JLabel();
        currentDateField=new javax.swing.JTextField();
        loveTimeField=new javax.swing.JTextField();
        loveTimeLabel=new javax.swing.JLabel();
        marryTimeLabel=new javax.swing.JLabel();
        marryTimeField=new javax.swing.JTextField();
        calculateButton=new javax.swing.JButton();
        knowDateField=new javax.swing.JTextField();
        knowDateLabel=new javax.swing.JLabel();
        knowTimeLabel=new javax.swing.JLabel();
        knowTimeField=new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("爱情计算器");
        setBackground(new java.awt.Color(255,255,255));

        loveDateLabel.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N
        loveDateLabel.setText("恋爱日期：");

        loveDateField.setEditable(false);
        loveDateField.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N

        marryDateField.setEditable(false);
        marryDateField.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N

        marryDateLabel.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N
        marryDateLabel.setText("结婚日期：");

        currentDateLabel.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N
        currentDateLabel.setText("当前日期：");

        currentDateField.setEditable(false);
        currentDateField.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N

        loveTimeField.setEditable(false);
        loveTimeField.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N

        loveTimeLabel.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N
        loveTimeLabel.setText("恋爱时间：");

        marryTimeLabel.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N
        marryTimeLabel.setText("结婚时间：");

        marryTimeField.setEditable(false);
        marryTimeField.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N

        calculateButton.setText("计算");
        calculateButton.addMouseListener(
                new java.awt.event.MouseAdapter()
                {
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        calculateButtonMouseClicked(evt);
                    }
                }
        );

        knowDateField.setEditable(false);
        knowDateField.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N

        knowDateLabel.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N
        knowDateLabel.setText("结识日期：");

        knowTimeLabel.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N
        knowTimeLabel.setText("结识时间：");

        knowTimeField.setEditable(false);
        knowTimeField.setFont(new java.awt.Font("微软雅黑",0,14)); // NOI18N

        javax.swing.GroupLayout layout=new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING
                                                                )
                                                                        .addComponent(marryTimeLabel)
                                                                        .addComponent(loveTimeLabel)
                                                                        .addComponent(knowTimeLabel)
                                                                        .addComponent(currentDateLabel)
                                                                        .addComponent(marryDateLabel)
                                                        )
                                                        .addComponent(loveDateLabel)
                                                        .addComponent(knowDateLabel)
                                        )
                                        .addGap(10,10,10)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(calculateButton)
                                                        .addComponent(
                                                                marryTimeField,javax.swing.GroupLayout.DEFAULT_SIZE,194,
                                                                Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                knowTimeField,javax.swing.GroupLayout.DEFAULT_SIZE,194,
                                                                Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                knowDateField,javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,194,Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                loveDateField,javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,194,Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                marryDateField,javax.swing.GroupLayout.DEFAULT_SIZE,194,
                                                                Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                currentDateField,javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                194,Short.MAX_VALUE
                                                        )
                                                        .addComponent(
                                                                loveTimeField,javax.swing.GroupLayout.DEFAULT_SIZE,194,
                                                                Short.MAX_VALUE
                                                        )
                                        )
                                        .addContainerGap()
                        )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,layout.createSequentialGroup()
                                        .addContainerGap(29,Short.MAX_VALUE)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                knowDateField,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(knowDateLabel)
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                loveDateField,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(loveDateLabel)
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                marryDateField,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(marryDateLabel)
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                currentDateField,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(currentDateLabel)
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                knowTimeField,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(knowTimeLabel)
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                loveTimeField,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(loveTimeLabel)
                                        )
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                marryTimeField,javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE
                                                        )
                                                        .addComponent(marryTimeLabel)
                                        )
                                        .addGap(14,14,14)
                                        .addComponent(calculateButton)
                                        .addContainerGap()
                        )
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_calculateButtonMouseClicked
    {//GEN-HEADEREND:event_calculateButtonMouseClicked
        // TODO add your handling code here:
        this.knowTimeField.setText(this.calculateDate(curDate,this.knowDate));
        this.loveTimeField.setText(this.calculateDate(curDate,this.loveDate));
        this.marryTimeField.setText(this.calculateDate(curDate,this.marryDate));
    }//GEN-LAST:event_calculateButtonMouseClicked

    private String calculateDate(String currentDate,String oldDate)
    {
        String result="";
        int first=4;
        int last=7;

        //计算年
        int cur=Integer.parseInt(currentDate.substring(0,first));
        int old=Integer.parseInt(oldDate.substring(0,first));
        int diff=cur-old;
        result+=(diff<1)?"":(diff+"年");

        //计算月
        cur=Integer.parseInt(currentDate.substring(first+1,last));
        old=Integer.parseInt(oldDate.substring(first+1,last));
        diff=cur-old;
        result+=(diff<1)?"":(diff+"个月");

        //计算天
        cur=Integer.parseInt(currentDate.substring(last+1));
        old=Integer.parseInt(oldDate.substring(last+1));
        diff=cur-old;
        result+=(diff<1)?"":(diff+"天");

        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName())
                    .log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName())
                    .log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName())
                    .log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoveCalculator.class.getName())
                    .log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable()
                {
                    public void run()
                    {
                        new LoveCalculator().setVisible(true);
                    }
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField currentDateField;
    private javax.swing.JLabel currentDateLabel;
    private javax.swing.JTextField knowDateField;
    private javax.swing.JLabel knowDateLabel;
    private javax.swing.JTextField knowTimeField;
    private javax.swing.JLabel knowTimeLabel;
    private javax.swing.JTextField loveDateField;
    private javax.swing.JLabel loveDateLabel;
    private javax.swing.JTextField loveTimeField;
    private javax.swing.JLabel loveTimeLabel;
    private javax.swing.JTextField marryDateField;
    private javax.swing.JLabel marryDateLabel;
    private javax.swing.JTextField marryTimeField;
    private javax.swing.JLabel marryTimeLabel;
    // End of variables declaration//GEN-END:variables
}
